---

- name: Copy kafka config
  template: 
    src: server.properties.j2 
    dest: "{{ kafkaDir }}/config/server.properties"
  notify: restart kafka

- name: Create logging dir
  file:
    path: "{{ loggingDir }}"
    state: directory